hospital_state = {
        'Hospital Sultanah Nora Ismail': 'Johor',
        'Hospital Sultanah Aminah': 'Johor',
        'Hospital Sultanah Bahiyah': 'Kedah',
        'Hospital Raja Perempuan Zainab II': 'Kelantan',
        'Hospital Melaka': 'Melaka',
        'Hospital Tuanku Jaafar': 'Negeri Sembilan',
        'Hospital Tengku Ampuan Afzan': 'Pahang',
        'Hospital Sultan Haji Ahmad Shah': 'Pahang',
        'Hospital Seberang Jaya': 'Penang',
        'Hospital Pulau Pinang': 'Penang',
        'Hospital Raja Permaisuri Bainun': 'Perak',
        'Hospital Taiping': 'Perak',
        'Hospital Seri Manjung': 'Perak',
        'Hospital Tengku Ampuan Rahimah': 'Selangor',
        'Hospital Sultanah Nur Zahirah': 'Terengganu',
        'Hospital Queen Elizabeth II': 'Sabah',
        'Hospital Duchess Of Kent': 'Sabah',
        'Hospital Tawau': 'Sabah',
        'Hospital Umum Sarawak': 'Sarawak',
        'Hospital Miri': 'Sarawak',
        'Hospital Sibu': 'Sarawak',
        'Pusat Darah Negara': 'Kuala Lumpur'
    }